version: 2

sources:
  - name: customer_data
    database: DEMO
    schema: PUBLIC
    tables:
      - name: "customer_demo"
        description: "Customer demo table"

models:
  - name: example_model
    description: "An example model"
    columns:
      - name: City
        description: "The city where the person is located"
        tests:
          - not_null
      - name: First_Name
        description: "The first name of the person"
        tests:
          - not_null
      - name: Last_Name
        description: "The last name of the person"
        tests:
          - not_null
      - name: Email
        description: "The email address of the person"
        tests:
          - not_null
          - unique

